language: generic

sudo: required
services:
  - docker


before_install:
  - docker build -t jpsagarm95/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jpsagarm95/docker-react npm run test